const sherwaniData = [
    {
      name: 'Men Velvet Sherwani Set',
      description: "Make a grand entrance with this Velvet Sherwani Set, featuring intricate embroidery and a regal silhouette. Perfect for weddings and special occasions, it exudes timeless charm.",
      price: 14999,
      images: ['https://m.media-amazon.com/images/I/81R9a6l34ZL._UX679_.jpg'],
      attributes: {
        Fabric: "Velvet",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "ROYAL VELVET",
        "Top fabric": "Velvet",
        "Bottom fabric": "Silk",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Embroidered",
        Color: "Maroon, Gold",
        Occasion: "Wedding, Reception",
        Neck: "Bandhgala",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 12
    },
    {
      name: 'Men Silk Sherwani Set',
      description: "Step into tradition with this exquisite Silk Sherwani Set, featuring intricate embroidery and a luxurious feel. Perfect for weddings and special occasions, it enhances your regal presence.",
      price: 10999,
      images: ['https://m.media-amazon.com/images/I/71twUYZ4-RL._UX679_.jpg'],
      attributes: {
        Fabric: "Silk",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "SILK ROYALTY",
        "Top fabric": "Silk",
        "Bottom fabric": "Silk",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Embroidered",
        Color: "Cream, Gold",
        Occasion: "Wedding, Reception",
        Neck: "High Neck",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 15
    },
    {
      name: 'Men Brocade Sherwani Set',
      description: "Dress up in this opulent Brocade Sherwani Set, featuring intricate brocade work and a sophisticated design. Perfect for weddings and formal events, it adds a touch of elegance.",
      price: 12999,
      images: ['https://m.media-amazon.com/images/I/91cTkbZr5yL._UX679_.jpg'],
      attributes: {
        Fabric: "Brocade",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "BROCADE ELEGANCE",
        "Top fabric": "Brocade",
        "Bottom fabric": "Silk",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Embroidered",
        Color: "Maroon",
        Occasion: "Wedding, Reception",
        Neck: "Bandhgala",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 10
    },
    {
      name: 'Men Embroidered Silk Sherwani Set',
      description: "Embrace sophistication with this Embroidered Silk Sherwani Set, featuring intricate embroidery and a luxurious feel. Perfect for weddings and grand celebrations.",
      price: 15999,
      images: ['https://m.media-amazon.com/images/I/71D-N1j5ZqL._UX679_.jpg'],
      attributes: {
        Fabric: "Silk",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "EMBROIDERED SILK",
        "Top fabric": "Silk",
        "Bottom fabric": "Silk",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Embroidered",
        Color: "White, Gold",
        Occasion: "Wedding, Reception",
        Neck: "Mandarin Collar",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 8
    },
    {
      name: 'Men Velvet Embroidered Sherwani Set',
      description: "Enhance your royal look with this Velvet Embroidered Sherwani Set, crafted from plush velvet and adorned with intricate embroidery. Ideal for weddings and special occasions.",
      price: 18999,
      categoryIds: category.map((cat) => cat._id),
      attributes: {
        Fabric: "Velvet",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "VELVET EMBROIDERY",
        "Top fabric": "Velvet",
        "Bottom fabric": "Silk",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Embroidered",
        Color: "Black, Gold",
        Occasion: "Wedding, Reception",
        Neck: "Bandhgala",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 10
    },
    {
      name: 'Men Banarasi Silk Sherwani Set',
      description: "Exude elegance with this Banarasi Silk Sherwani Set, featuring intricate Banarasi weaving and a regal silhouette. Perfect for weddings and grand celebrations.",
      price: 21999,
      images: ['https://m.media-amazon.com/images/I/81je87DP36L._UX679_.jpg'],
      attributes: {
        Fabric: "Banarasi Silk",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "BANARASI WEAVE",
        "Top fabric": "Banarasi Silk",
        "Bottom fabric": "Banarasi Silk",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Woven",
        Color: "Royal Blue, Gold",
        Occasion: "Wedding, Festive",
        Neck: "Mandarin Collar",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 12
    },
    {
      name: 'Men Embroidered Velvet Sherwani Set',
      description: "Achieve a majestic look with this Embroidered Velvet Sherwani Set, featuring intricate embroidery on luxurious velvet. Ideal for weddings and formal occasions.",
      price: 17999,
      images: ['https://m.media-amazon.com/images/I/61aC-dXNB5L._UX679_.jpg'],
      attributes: {
        Fabric: "Velvet",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "VELVET EMBROIDERY",
        "Top fabric": "Velvet",
        "Bottom fabric": "Velvet",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Embroidered",
        Color: "Maroon, Gold",
        Occasion: "Wedding, Reception",
        Neck: "Bandhgala",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 8
    },
    {
      name: 'Men Embellished Silk Sherwani Set',
      description: "Step into luxury with this Embellished Silk Sherwani Set, featuring exquisite embellishments and a regal silhouette. Perfect for weddings and special celebrations.",
      price: 24999,
      images: ['https://m.media-amazon.com/images/I/61hH7-zxRRL._UX679_.jpg'],
      attributes: {
        Fabric: "Silk",
        Type: "Sherwani Set",
        "Sales Package": "Sherwani, Churidar",
        "Style Code": "SILK EMBELLISHMENT",
        "Top fabric": "Silk",
        "Bottom fabric": "Silk",
        "Top type": "Sherwani",
        "Bottom type": "Churidar",
        Pattern: "Embellished",
        Color: "Cream, Gold",
        Occasion: "Wedding, Reception",
        Neck: "High Neck",
        "Fabric care": "Dry Clean Only"
      },
      stockQuantity: 10
    },
    {
        name: 'Men Raw Silk Sherwani Set',
        description: "Crafted from raw silk, this Sherwani Set exudes elegance with its minimalistic yet sophisticated design. Ideal for weddings and formal occasions.",
        price: 16999,
        images: ['https://m.media-amazon.com/images/I/71eR9T9LqcL._UX679_.jpg'],
        attributes: {
          Fabric: "Raw Silk",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "RAW SILK ELEGANCE",
          "Top fabric": "Raw Silk",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "Navy Blue, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Bandhgala",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 10
      },
      {
        name: 'Men Art Silk Sherwani Set',
        description: "Indulge in luxury with this Art Silk Sherwani Set, featuring a blend of comfort and elegance. Perfect for weddings and special celebrations.",
        price: 13999,
        images: ['https://m.media-amazon.com/images/I/81w8d7pzUjL._UX679_.jpg'],
        attributes: {
          Fabric: "Art Silk",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "ART SILK ELEGANCE",
          "Top fabric": "Art Silk",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "Beige, Gold",
          Occasion: "Wedding, Reception",
          Neck: "High Neck",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 15
      },
      {
        name: 'Men Georgette Sherwani Set',
        description: "Elevate your style with this Georgette Sherwani Set, featuring a lightweight fabric and intricate embroidery. Ideal for weddings and festive occasions.",
        price: 17999,
        images: ['https://m.media-amazon.com/images/I/81ZQq3RWyDL._UX679_.jpg'],
        attributes: {
          Fabric: "Georgette",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "GEORGETTE ELEGANCE",
          "Top fabric": "Georgette",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "Black, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Mandarin Collar",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 12
      },
      {
        name: 'Men Cotton Silk Sherwani Set',
        description: "Stay comfortable yet stylish with this Cotton Silk Sherwani Set, featuring a blend of cotton and silk fabrics. Perfect for weddings and formal events.",
        price: 12999,
        images: ['https://m.media-amazon.com/images/I/81t6B1zSZOL._UX679_.jpg'],
        attributes: {
          Fabric: "Cotton Silk",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "COTTON SILK ELEGANCE",
          "Top fabric": "Cotton Silk",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "White, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Bandhgala",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 10
      },
      {
        name: 'Men Jacquard Sherwani Set',
        description: "Make a statement with this Jacquard Sherwani Set, featuring intricate jacquard weaving and a sophisticated design. Ideal for weddings and formal occasions.",
        price: 18999,
        images: ['https://m.media-amazon.com/images/I/61CJLYA5ewL._UX679_.jpg'],
        attributes: {
          Fabric: "Jacquard",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "JACQUARD ELEGANCE",
          "Top fabric": "Jacquard",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Woven",
          Color: "Red, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Bandhgala",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 8
      },
      {
        name: 'Men Embroidered Jamawar Sherwani Set',
        description: "Elevate your style with this Embroidered Jamawar Sherwani Set, featuring intricate embroidery on luxurious jamawar fabric. Perfect for weddings and special occasions.",
        price: 23999,
        images: ['https://m.media-amazon.com/images/I/71-VNfA7DzL._UX679_.jpg'],
        attributes: {
          Fabric: "Jamawar",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "JAMAWAR ELEGANCE",
          "Top fabric": "Jamawar",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "Gold, Maroon",
          Occasion: "Wedding, Reception",
          Neck: "High Neck",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 12
      },
      {
        name: 'Men Silk Brocade Sherwani Set',
        description: "Step into tradition with this Silk Brocade Sherwani Set, featuring intricate brocade work and a luxurious silk fabric. Perfect for weddings and formal occasions.",
        price: 17999,
        images: ['https://m.media-amazon.com/images/I/71J9tXhv3VL._UX679_.jpg'],
        attributes: {
          Fabric: "Silk Brocade",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "SILK BROCADE ELEGANCE",
          "Top fabric": "Silk Brocade",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Brocade",
          Color: "Blue, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Mandarin Collar",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 15
      },
      {
        name: 'Men Art Silk Embroidered Sherwani Set',
        description: "Add elegance to your ensemble with this Art Silk Embroidered Sherwani Set, featuring intricate embroidery and a rich art silk fabric. Perfect for weddings and special occasions.",
        price: 19999,
        images: ['https://m.media-amazon.com/images/I/81sZqlFGQHL._UX679_.jpg'],
        attributes: {
          Fabric: "Art Silk",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "ART SILK EMBROIDERY",
          "Top fabric": "Art Silk",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "Green, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Bandhgala",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 10
      },
      {
        name: 'Men Banarasi Brocade Sherwani Set',
        description: "Celebrate in style with this Banarasi Brocade Sherwani Set, featuring exquisite Banarasi brocade weaving and a royal silhouette. Perfect for weddings and festive occasions.",
        price: 25999,
        images: ['https://m.media-amazon.com/images/I/81B8LsD64uL._UX679_.jpg'],
        attributes: {
          Fabric: "Banarasi Brocade",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "BANARASI BROCADE",
          "Top fabric": "Banarasi Brocade",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Brocade",
          Color: "Purple, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Mandarin Collar",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 12
      },
      {
        name: 'Men Embroidered Cotton Sherwani Set',
        description: "Stay comfortable yet stylish with this Embroidered Cotton Sherwani Set, featuring intricate embroidery on soft cotton fabric. Perfect for weddings and formal events.",
        price: 14999,
        images: ['https://m.media-amazon.com/images/I/81TW1kPK3vL._UX679_.jpg'],
        attributes: {
          Fabric: "Cotton",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "COTTON EMBROIDERY",
          "Top fabric": "Cotton",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "White, Gold",
          Occasion: "Wedding, Reception",
          Neck: "High Neck",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 15
      },
      {
        name: 'Men Raw Silk Embroidered Sherwani Set',
        description: "Achieve a sophisticated look with this Raw Silk Embroidered Sherwani Set, featuring intricate embroidery on rich raw silk fabric. Perfect for weddings and formal occasions.",
        price: 18999,
        images: ['https://m.media-amazon.com/images/I/71oB4mD9BhL._UX679_.jpg'],
        attributes: {
          Fabric: "Raw Silk",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "RAW SILK EMBROIDERY",
          "Top fabric": "Raw Silk",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "Blue, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Bandhgala",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 10
      },
      {
        name: 'Men Tussar Silk Sherwani Set',
        description: "Drape yourself in luxury with this Tussar Silk Sherwani Set, featuring a rich tussar silk fabric and intricate embroidery. Perfect for weddings and grand celebrations.",
        price: 20999,
        images: ['https://m.media-amazon.com/images/I/71x01lM+QDL._UX679_.jpg'],
        attributes: {
          Fabric: "Tussar Silk",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "TUSSAR SILK ELEGANCE",
          "Top fabric": "Tussar Silk",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "Cream, Gold",
          Occasion: "Wedding, Reception",
          Neck: "High Neck",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 12
      },
      {
        name: 'Men Linen Embroidered Sherwani Set',
        description: "Stay cool and stylish with this Linen Embroidered Sherwani Set, featuring intricate embroidery on lightweight linen fabric. Perfect for summer weddings and formal occasions.",
        price: 16999,
        images: ['https://m.media-amazon.com/images/I/71vuph8wypL._UX679_.jpg'],
        attributes: {
          Fabric: "Linen",
          Type: "Sherwani Set",
          "Sales Package": "Sherwani, Churidar",
          "Style Code": "LINEN EMBROIDERY",
          "Top fabric": "Linen",
          "Bottom fabric": "Silk",
          "Top type": "Sherwani",
          "Bottom type": "Churidar",
          Pattern: "Embroidered",
          Color: "White, Gold",
          Occasion: "Wedding, Reception",
          Neck: "Bandhgala",
          "Fabric care": "Dry Clean Only"
        },
        stockQuantity: 15
      }
    ];

export default sherwaniData;